### ISSUE TITLE
Installation on Debian 10 (buster)

### ISSUE THREAD

**Issue by okitupadmin** [NoxInmortus/role-ispconfig#2]
Hi!

I'm trying to execute the playbook on Debian 10, and I found my first issue:
`fatal: [ok00up88]: FAILED! => {"changed": false, "msg": "No package matching 'zoo' is available"}`

It's a small one and I will try to continue with all the playbook, but I want to know if you are working to move it to Debian 10.

Thanks in advance!

**Comment by NoxInmortus** [comment]
Hello @okitupadmin 

I'm not working with ISPConfig anymore so it is not in my todo to upgrade this role.

The role is pretty huge, and I know there is a lot that have been bad-written. It would be very time consuming for me to do all this work knowing I dont use it anymore.

However, I would gladely review and merge any pull requests.

**Comment by okitupadmin** [comment]
Thanks @NoxInmortus for your response ;)

**Comment by NoxInmortus** [comment]
Hello @okitupadmin 

You may want to read #3 

Sorry for the noise if you don't.
